// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class AdminActionLog
{
    public int AdminActionLogId { get; set; }

    public string Area { get; set; }

    public string ActionName { get; set; }

    public string TargetType { get; set; }

    public int? TargetId { get; set; }

    public string Summary { get; set; }

    public int? ActorUserId { get; set; }

    public string MetadataJson { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<ModerationAudit> ModerationAudits { get; set; } = new List<ModerationAudit>();

    public virtual ICollection<SettlementAudit> SettlementAudits { get; set; } = new List<SettlementAudit>();
}