// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class AdsCampaign
{
    public int AdsCampaignId { get; set; }

    public int WalletId { get; set; }

    public int SellerId { get; set; }

    public int? CampaignId { get; set; }

    public string Name { get; set; }

    public string Channel { get; set; }

    public string Status { get; set; }

    public decimal DailyBudget { get; set; }

    public decimal TotalBudget { get; set; }

    public decimal SpendToDate { get; set; }

    public DateTime StartAt { get; set; }

    public DateTime EndAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<AdsSpendLedger> AdsSpendLedgers { get; set; } = new List<AdsSpendLedger>();

    public virtual Campaign Campaign { get; set; }

    public virtual SellerAdsWallet Wallet { get; set; }
}