// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class AdsSpendLedger
{
    public int SpendId { get; set; }

    public int WalletId { get; set; }

    public int SellerId { get; set; }

    public int? AdsCampaignId { get; set; }

    public decimal Amount { get; set; }

    public string SpendType { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual AdsCampaign AdsCampaign { get; set; }

    public virtual SellerAdsWallet Wallet { get; set; }
}