// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class CampaignProductSlot
{
    public int SlotId { get; set; }

    public int CampaignId { get; set; }

    public int? ParticipationId { get; set; }

    public int SellerId { get; set; }

    public int ProductId { get; set; }

    public string Status { get; set; }

    public decimal? FlashSalePrice { get; set; }

    public int? InventoryLimit { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public virtual Campaign Campaign { get; set; }

    public virtual CampaignSellerParticipation Participation { get; set; }
}