// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class CampaignSellerParticipation
{
    public int ParticipationId { get; set; }

    public int CampaignId { get; set; }

    public int SellerId { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public decimal? DiscountPercent { get; set; }

    public int? RequestedSlots { get; set; }

    public int? ApprovedSlots { get; set; }

    public DateTime RequestedAt { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public int? ReviewedBy { get; set; }

    public virtual Campaign Campaign { get; set; }

    public virtual ICollection<CampaignProductSlot> CampaignProductSlots { get; set; } = new List<CampaignProductSlot>();
}