// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class Campaign
{
    public int CampaignId { get; set; }

    public string Name { get; set; }

    public string CampaignType { get; set; }

    public string Description { get; set; }

    public DateTime RegistrationStartAt { get; set; }

    public DateTime RegistrationEndAt { get; set; }

    public DateTime StartAt { get; set; }

    public DateTime EndAt { get; set; }

    public string Status { get; set; }

    public decimal? BudgetAmount { get; set; }

    public bool IsFeatured { get; set; }

    public int? VoucherCouponId { get; set; }

    public int? CreatedBy { get; set; }

    public int? ApprovedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public virtual ICollection<AdsCampaign> AdsCampaigns { get; set; } = new List<AdsCampaign>();

    public virtual ICollection<CampaignProductSlot> CampaignProductSlots { get; set; } = new List<CampaignProductSlot>();

    public virtual ICollection<CampaignSellerParticipation> CampaignSellerParticipations { get; set; } = new List<CampaignSellerParticipation>();

    public virtual Coupon VoucherCoupon { get; set; }
}