// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class CancelReason
{
    public int CancelReasonId { get; set; }

    public string ReasonCode { get; set; }

    public string ReasonText { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<SellerOrder> SellerOrders { get; set; } = new List<SellerOrder>();
}