// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class CartItem
{
    public int CartItemId { get; set; }

    public int CartId { get; set; }

    public int ProductId { get; set; }

    public int SellerId { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public string SnapshotSellerName { get; set; }

    public string SnapshotProductName { get; set; }

    public string SnapshotImageFileName { get; set; }

    public string SnapshotUnitSymbol { get; set; }

    public virtual Cart Cart { get; set; }
}
