// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class CommunicationTemplate
{
    public int CommunicationTemplateId { get; set; }

    public string TemplateName { get; set; }

    public string EventType { get; set; }

    public string Channel { get; set; }

    public string Locale { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public bool IsActive { get; set; }

    public int Version { get; set; }

    public int? LastEditedByUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<NotificationPolicyRule> NotificationPolicyRules { get; set; } = new List<NotificationPolicyRule>();
}