// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class ContactMessage
{
    public int Id { get; set; }

    public string SenderName { get; set; }

    public string SenderEmail { get; set; }

    public string SenderPhone { get; set; }

    public string Subject { get; set; }

    public string Message { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Status { get; set; }

    public string AdminNote { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }
}