// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class Coupon
{
    public int CouponId { get; set; }

    public string Code { get; set; }

    public decimal DiscountValue { get; set; }

    public DateOnly ExpiryDate { get; set; }

    public decimal? MinOrderValue { get; set; }

    public string DiscountType { get; set; }

    public bool IsActive { get; set; }

    public int? UsageLimit { get; set; }

    public int UsedCount { get; set; }

    public string Description { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public decimal? MaxDiscountAmount { get; set; }

    public virtual ICollection<CouponDistribution> CouponDistributions { get; set; } = new List<CouponDistribution>();

    public virtual ICollection<CouponUsageHistory> CouponUsageHistories { get; set; } = new List<CouponUsageHistory>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}