// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class CouponUsageHistory
{
    public int UsageId { get; set; }

    public int CouponId { get; set; }

    public int UserId { get; set; }

    public int OrderId { get; set; }

    public decimal DiscountAmount { get; set; }

    public DateTime UsedDate { get; set; }

    public string Ipaddress { get; set; }

    public string UserAgent { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Order Order { get; set; }
}