// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class CouponDistribution
{
    public int DistributionId { get; set; }

    public int CouponId { get; set; }

    public int UserId { get; set; }

    public DateTime SentDate { get; set; }

    public int? SentBy { get; set; }

    public bool IsUsed { get; set; }

    public DateTime? UsedDate { get; set; }

    public string Channel { get; set; }

    public string Status { get; set; }

    public virtual Coupon Coupon { get; set; }
}