// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class CustomerNotification
{
    public int NotificationId { get; set; }

    public int UserId { get; set; }

    public int OrderId { get; set; }

    public string NotificationType { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public bool? IsRead { get; set; }

    public bool? IsPushNotification { get; set; }

    public string PopupType { get; set; }

    public string PopupImageUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public DateTime? ReadAt { get; set; }
}
