// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FreshFarm.Ordering.Api.Models;

public partial class FreshFarmOrderingDBContext : DbContext
{
    public FreshFarmOrderingDBContext(DbContextOptions<FreshFarmOrderingDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CancelReason> CancelReasons { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartItem> CartItems { get; set; }

    public virtual DbSet<ContactMessage> ContactMessages { get; set; }

    public virtual DbSet<Coupon> Coupons { get; set; }

    public virtual DbSet<CouponDistribution> CouponDistributions { get; set; }

    public virtual DbSet<CouponUsageHistory> CouponUsageHistories { get; set; }

    public virtual DbSet<CustomerNotification> CustomerNotifications { get; set; }

    public virtual DbSet<InventoryReservation> InventoryReservations { get; set; }

    public virtual DbSet<LoyaltyConfig> LoyaltyConfigs { get; set; }

    public virtual DbSet<LoyaltyPointHistory> LoyaltyPointHistories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<OrderStatusHistory> OrderStatusHistories { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentTransaction> PaymentTransactions { get; set; }

    public virtual DbSet<Payout> Payouts { get; set; }

    public virtual DbSet<PayoutItem> PayoutItems { get; set; }

    public virtual DbSet<ReconciliationLog> ReconciliationLogs { get; set; }

    public virtual DbSet<RefundTransaction> RefundTransactions { get; set; }

    public virtual DbSet<ReturnRequest> ReturnRequests { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<ReviewReport> ReviewReports { get; set; }

    public virtual DbSet<SellerOrder> SellerOrders { get; set; }

    public virtual DbSet<SellerOrderItem> SellerOrderItems { get; set; }

    public virtual DbSet<Shipment> Shipments { get; set; }

    public virtual DbSet<ShipmentEvent> ShipmentEvents { get; set; }

    public virtual DbSet<Shipping> Shippings { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    public virtual DbSet<StatusType> StatusTypes { get; set; }

    public virtual DbSet<SupportConversation> SupportConversations { get; set; }

    public virtual DbSet<SupportMessage> SupportMessages { get; set; }

    public virtual DbSet<SupportMessageReaction> SupportMessageReactions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CancelReason>(entity =>
        {
            entity.HasKey(e => e.CancelReasonId).HasName("PK__CancelRe__9D7E8F962F0E33D0");

            entity.HasIndex(e => e.ReasonCode, "UQ__CancelRe__A6278DA30C8440EF").IsUnique();

            entity.Property(e => e.CancelReasonId).HasColumnName("CancelReasonID");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ReasonCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ReasonText)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.CartId).HasName("PK__Cart__51BCD797FAF813EA");

            entity.ToTable("Cart");

            entity.HasIndex(e => e.UserId, "IX_Cart_UserID").IsUnique();

            entity.Property(e => e.CartId).HasColumnName("CartID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<CartItem>(entity =>
        {
            entity.HasKey(e => e.CartItemId).HasName("PK__CartItem__488B0B2A7E7BEB70");

            entity.ToTable("CartItem");

            entity.HasIndex(e => new { e.CartId, e.ProductId }, "IX_CartItem_Cart_Product").IsUnique();

            entity.Property(e => e.CartItemId).HasColumnName("CartItemID");
            entity.Property(e => e.CartId).HasColumnName("CartID");
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.Quantity).HasDefaultValue(1);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Cart).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.CartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItem__CartID__2EDAF651");
        });

        modelBuilder.Entity<ContactMessage>(entity =>
        {
            entity.Property(e => e.AdminNote).HasMaxLength(1000);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ContactMessages_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_ContactMessages_IsDeleted");
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.ProcessedAt).HasColumnType("datetime");
            entity.Property(e => e.SenderEmail)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.SenderName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.SenderPhone).HasMaxLength(30);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("new")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ContactMessages_Status");
            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(300);
        });

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.HasKey(e => e.CouponId).HasName("PK__Coupons__384AF1DA1AEB61D4");

            entity.HasIndex(e => new { e.IsActive, e.ExpiryDate }, "IX_Coupons_Active_Expiry");

            entity.HasIndex(e => e.Code, "IX_Coupons_Code");

            entity.HasIndex(e => e.ExpiryDate, "IX_Coupons_ExpiryDate");

            entity.HasIndex(e => e.IsActive, "IX_Coupons_IsActive");

            entity.HasIndex(e => e.Code, "UQ__Coupons__A25C5AA7914A76AA").IsUnique();

            entity.Property(e => e.CouponId).HasColumnName("CouponID");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Coupons_CreatedDate")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.DiscountType)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("fixed")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Coupons_DiscountType");
            entity.Property(e => e.DiscountValue).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Coupons_IsActive");
            entity.Property(e => e.MaxDiscountAmount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.MinOrderValue).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.UsedCount).HasAnnotation("Relational:DefaultConstraintName", "DF_Coupons_UsedCount");
        });

        modelBuilder.Entity<CouponDistribution>(entity =>
        {
            entity.HasKey(e => e.DistributionId).HasName("PK__CouponDi__3226272F69F0E4C1");

            entity.ToTable("CouponDistribution");

            entity.HasIndex(e => e.CouponId, "IX_CouponDistribution_CouponID");

            entity.HasIndex(e => e.IsUsed, "IX_CouponDistribution_IsUsed");

            entity.HasIndex(e => e.Status, "IX_CouponDistribution_Status");

            entity.HasIndex(e => e.UserId, "IX_CouponDistribution_UserID");

            entity.HasIndex(e => new { e.CouponId, e.UserId }, "UQ_CouponDistribution_Coupon_User").IsUnique();

            entity.Property(e => e.DistributionId).HasColumnName("DistributionID");
            entity.Property(e => e.Channel).HasMaxLength(50);
            entity.Property(e => e.CouponId).HasColumnName("CouponID");
            entity.Property(e => e.SentDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Sent");
            entity.Property(e => e.UsedDate).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Coupon).WithMany(p => p.CouponDistributions)
                .HasForeignKey(d => d.CouponId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CD_Coupon");
        });

        modelBuilder.Entity<CouponUsageHistory>(entity =>
        {
            entity.HasKey(e => e.UsageId).HasName("PK__CouponUs__29B197C004176640");

            entity.ToTable("CouponUsageHistory");

            entity.HasIndex(e => e.CouponId, "IX_CouponUsageHistory_CouponID");

            entity.HasIndex(e => e.OrderId, "IX_CouponUsageHistory_OrderID");

            entity.HasIndex(e => e.UsedDate, "IX_CouponUsageHistory_UsedDate");

            entity.HasIndex(e => e.UserId, "IX_CouponUsageHistory_UserID");

            entity.Property(e => e.UsageId).HasColumnName("UsageID");
            entity.Property(e => e.CouponId).HasColumnName("CouponID");
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(50)
                .HasColumnName("IPAddress");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.UsedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserAgent).HasMaxLength(500);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Coupon).WithMany(p => p.CouponUsageHistories)
                .HasForeignKey(d => d.CouponId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CUH_Coupon");

            entity.HasOne(d => d.Order).WithMany(p => p.CouponUsageHistories)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CUH_Order");
        });

        modelBuilder.Entity<CustomerNotification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Customer__20CF2E3289B0C6AB");

            entity.HasIndex(e => e.OrderId, "IX_CustomerNotifications_OrderID");

            entity.HasIndex(e => e.UserId, "IX_CustomerNotifications_UserID");

            entity.Property(e => e.NotificationId).HasColumnName("NotificationID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsPushNotification).HasDefaultValue(false);
            entity.Property(e => e.IsRead).HasDefaultValue(false);
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.NotificationType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.ReadAt).HasColumnType("datetime");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<InventoryReservation>(entity =>
        {
            entity.HasKey(e => e.ReservationId).HasName("PK__Inventor__B7EE5F04BE112097");

            entity.ToTable("InventoryReservation");

            entity.Property(e => e.ReservationId).HasColumnName("ReservationID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpiresAt).HasColumnType("datetime");
            entity.Property(e => e.InventoryId).HasColumnName("InventoryID");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.SellerOrderItemId).HasColumnName("SellerOrderItemID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Order).WithMany(p => p.InventoryReservations)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_InventoryReservation_Order");

            entity.HasOne(d => d.SellerOrderItem).WithMany(p => p.InventoryReservations)
                .HasForeignKey(d => d.SellerOrderItemId)
                .HasConstraintName("FK_InventoryReservation_SOI");
        });

        modelBuilder.Entity<LoyaltyConfig>(entity =>
        {
            entity.HasKey(e => e.ConfigId).HasName("PK__LoyaltyC__C3BC333C787936AA");

            entity.ToTable("LoyaltyConfig");

            entity.Property(e => e.ConfigId).HasColumnName("ConfigID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_LC_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.EarnRate)
                .HasDefaultValue(0.01m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_LC_EarnRate")
                .HasColumnType("decimal(9, 6)");
            entity.Property(e => e.IncludeShippingFee).HasAnnotation("Relational:DefaultConstraintName", "DF_LC_IncludeShip");
            entity.Property(e => e.PaidKeywords).HasMaxLength(400);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_LC_UpdatedAt")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<LoyaltyPointHistory>(entity =>
        {
            entity.HasKey(e => e.PointHistoryId).HasName("PK__LoyaltyP__DBE13EF7015CFA30");

            entity.ToTable("LoyaltyPointHistory");

            entity.HasIndex(e => e.OrderId, "IX_LPH_OrderID");

            entity.HasIndex(e => new { e.UserId, e.CreatedAt }, "IX_LPH_UserID").IsDescending(false, true);

            entity.Property(e => e.PointHistoryId).HasColumnName("PointHistoryID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_LPH_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Direction)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.Reason).HasMaxLength(255);
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BAF4CCB8F90");

            entity.HasIndex(e => new { e.Status, e.OrderDate, e.OrderId }, "IX_Orders_Status_OrderDate_OrderID");

            entity.HasIndex(e => new { e.UserId, e.Status, e.PaidAt }, "IX_Orders_User_Status_PaidAt");

            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.BuyerEmail).HasMaxLength(200);
            entity.Property(e => e.BuyerFullName).HasMaxLength(100);
            entity.Property(e => e.BuyerPhone).HasMaxLength(20);
            entity.Property(e => e.CouponId).HasColumnName("CouponID");
            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.OrderNote).HasMaxLength(255);
            entity.Property(e => e.PaidAt).HasColumnType("datetime");
            entity.Property(e => e.PaymentStatus).HasMaxLength(20);
            entity.Property(e => e.PointsEarned).HasAnnotation("Relational:DefaultConstraintName", "DF_Orders_PointsEarned");
            entity.Property(e => e.PointsRedeemed).HasAnnotation("Relational:DefaultConstraintName", "DF_Orders_PointsRedeemed");
            entity.Property(e => e.ShippingFee)
                .HasDefaultValue(15000m)
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Pending");
            entity.Property(e => e.StatusId).HasColumnName("StatusID");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Coupon).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CouponId)
                .HasConstraintName("FK__Orders__CouponID__3A4CA8FD");

            entity.HasOne(d => d.StatusNavigation).WithMany(p => p.Orders)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK_Orders_Status");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.OrderDetailId).HasName("PK__OrderDet__D3B9D30CBC689489");

            entity.ToTable("OrderDetail");

            entity.Property(e => e.OrderDetailId).HasColumnName("OrderDetailID");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.Quantity).HasDefaultValue(1);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UnitSymbol).HasMaxLength(20);

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Order__395884C4");
        });

        modelBuilder.Entity<OrderStatusHistory>(entity =>
        {
            entity.HasKey(e => e.HistoryId).HasName("PK__OrderSta__4D7B4ADD928419E1");

            entity.ToTable("OrderStatusHistory");

            entity.Property(e => e.HistoryId).HasColumnName("HistoryID");
            entity.Property(e => e.ActorId).HasColumnName("ActorID");
            entity.Property(e => e.ActorType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.EntityId).HasColumnName("EntityID");
            entity.Property(e => e.EntityType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.NewStatus)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.Note).HasMaxLength(500);
            entity.Property(e => e.OldStatus).HasMaxLength(30);
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payment__9B556A588FA72E9D");

            entity.ToTable("Payment");

            entity.HasIndex(e => new { e.OrderId, e.PaymentDate }, "IX_Payment_Order_Paid");

            entity.HasIndex(e => new { e.OrderId, e.PaymentMethod, e.PaymentDate }, "IX_Payments_OrderID_PaymentMethod_PaymentDate");

            entity.Property(e => e.PaymentId).HasColumnName("PaymentID");
            entity.Property(e => e.AccountName).HasMaxLength(100);
            entity.Property(e => e.AccountNumber).HasMaxLength(50);
            entity.Property(e => e.BankName).HasMaxLength(100);
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.PaymentDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PaymentStatus)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Chưa thanh toán");
            entity.Property(e => e.TransactionCode).HasMaxLength(100);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Order).WithMany(p => p.Payments)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__OrderID__3C34F16F");
        });

        modelBuilder.Entity<PaymentTransaction>(entity =>
        {
            entity.HasKey(e => e.PaymentTxnId).HasName("PK__PaymentT__F1E4F1947DF6990F");

            entity.Property(e => e.PaymentTxnId).HasColumnName("PaymentTxnID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Currency)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValue("VND");
            entity.Property(e => e.FailureCode).HasMaxLength(50);
            entity.Property(e => e.FailureMessage).HasMaxLength(255);
            entity.Property(e => e.FeeAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Method)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.PaidAt).HasColumnType("datetime");
            entity.Property(e => e.Provider)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProviderRef).HasMaxLength(100);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30);

            entity.HasOne(d => d.Order).WithMany(p => p.PaymentTransactions)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentTxn_Order");
        });

        modelBuilder.Entity<Payout>(entity =>
        {
            entity.HasKey(e => e.PayoutId).HasName("PK__Payouts__35C3DFAE9DF87565");

            entity.Property(e => e.PayoutId).HasColumnName("PayoutID");
            entity.Property(e => e.AmountGross).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.AmountNet)
                .HasComputedColumnSql("([AmountGross]-[FeeAmount])", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FeeAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PaidAt).HasColumnType("datetime");
            entity.Property(e => e.PaymentTxnId).HasColumnName("PaymentTxnID");
            entity.Property(e => e.ScheduledAt).HasColumnType("datetime");
            entity.Property(e => e.SellerId).HasColumnName("SellerID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.PaymentTxn).WithMany(p => p.Payouts)
                .HasForeignKey(d => d.PaymentTxnId)
                .HasConstraintName("FK_Payouts_PaymentTxn");
        });

        modelBuilder.Entity<PayoutItem>(entity =>
        {
            entity.HasKey(e => e.PayoutItemId).HasName("PK__PayoutIt__3414EEFEFA459973");

            entity.Property(e => e.PayoutItemId).HasColumnName("PayoutItemID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.PayoutId).HasColumnName("PayoutID");
            entity.Property(e => e.SellerOrderId).HasColumnName("SellerOrderID");

            entity.HasOne(d => d.Payout).WithMany(p => p.PayoutItems)
                .HasForeignKey(d => d.PayoutId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PayoutItems_Payout");

            entity.HasOne(d => d.SellerOrder).WithMany(p => p.PayoutItems)
                .HasForeignKey(d => d.SellerOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PayoutItems_SellerOrder");
        });

        modelBuilder.Entity<ReconciliationLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__Reconcil__5E5499A8B43A438A");

            entity.ToTable("ReconciliationLog");

            entity.HasIndex(e => new { e.PaymentId, e.OrderId, e.CreatedAt }, "IX_ReconciliationLog_Payment_Order_CreatedAt").IsDescending(false, false, true);

            entity.Property(e => e.LogId).HasColumnName("LogID");
            entity.Property(e => e.ActionType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AdminId).HasColumnName("AdminID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Note).HasMaxLength(500);
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.PaymentId).HasColumnName("PaymentID");

            entity.HasOne(d => d.Order).WithMany(p => p.ReconciliationLogs)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReconciliationLog_Order");

            entity.HasOne(d => d.Payment).WithMany(p => p.ReconciliationLogs)
                .HasForeignKey(d => d.PaymentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReconciliationLog_Payment");
        });

        modelBuilder.Entity<RefundTransaction>(entity =>
        {
            entity.HasKey(e => e.RefundId).HasName("PK__RefundTr__725AB90050097E37");

            entity.Property(e => e.RefundId).HasColumnName("RefundID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Channel)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PaymentTxnId).HasColumnName("PaymentTxnID");
            entity.Property(e => e.ProcessedAt).HasColumnType("datetime");
            entity.Property(e => e.ReferenceCode).HasMaxLength(100);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30);

            entity.HasOne(d => d.PaymentTxn).WithMany(p => p.RefundTransactions)
                .HasForeignKey(d => d.PaymentTxnId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RefundTransactions_PaymentTxn");
        });

        modelBuilder.Entity<ReturnRequest>(entity =>
        {
            entity.HasKey(e => e.ReturnId).HasName("PK__ReturnRe__F445E988BD05394F");

            entity.Property(e => e.ReturnId).HasColumnName("ReturnID");
            entity.Property(e => e.ApprovedAt).HasColumnType("datetime");
            entity.Property(e => e.CompletedAt).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.ReasonCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RefundAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.RequestedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Resolution)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.SellerId).HasColumnName("SellerID");
            entity.Property(e => e.SellerOrderItemId).HasColumnName("SellerOrderItemID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30);

            entity.HasOne(d => d.SellerOrderItem).WithMany(p => p.ReturnRequests)
                .HasForeignKey(d => d.SellerOrderItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReturnRequests_SOI");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.ToTable("Review");

            entity.HasIndex(e => new { e.IsDeleted, e.CreatedAt }, "IX_Review_IsDeleted_CreatedAt").IsDescending(false, true);

            entity.HasIndex(e => new { e.ProductId, e.CreatedAt }, "IX_Review_Product_CreatedAt").IsDescending(false, true);

            entity.Property(e => e.ReviewId).HasColumnName("ReviewID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Review_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.IsApproved).HasAnnotation("Relational:DefaultConstraintName", "DF_Review_IsApproved");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_Review_IsDeleted");
            entity.Property(e => e.IsEdited).HasAnnotation("Relational:DefaultConstraintName", "DF_Review_IsEdited");
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.ReplyToNavigation).WithMany(p => p.InverseReplyToNavigation)
                .HasForeignKey(d => d.ReplyTo)
                .HasConstraintName("FK_Review_ReplyTo");
        });

        modelBuilder.Entity<ReviewReport>(entity =>
        {
            entity.HasKey(e => e.ReportId);

            entity.ToTable("ReviewReport");

            entity.HasIndex(e => new { e.ReviewId, e.Status, e.CreatedAt }, "IX_ReviewReport_Review").IsDescending(false, false, true);

            entity.Property(e => e.ReportId).HasColumnName("ReportID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ReviewReport_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Note).HasMaxLength(1000);
            entity.Property(e => e.Reason).HasMaxLength(500);
            entity.Property(e => e.ReporterUserId).HasColumnName("ReporterUserID");
            entity.Property(e => e.ReviewId).HasColumnName("ReviewID");

            entity.HasOne(d => d.Review).WithMany(p => p.ReviewReports)
                .HasForeignKey(d => d.ReviewId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReviewReport_Review");
        });

        modelBuilder.Entity<SellerOrder>(entity =>
        {
            entity.HasKey(e => e.SellerOrderId).HasName("PK__SellerOr__EE1F8CF4BF4B2300");

            entity.Property(e => e.SellerOrderId).HasColumnName("SellerOrderID");
            entity.Property(e => e.CancelReasonId).HasColumnName("CancelReasonID");
            entity.Property(e => e.CancelledBy).HasMaxLength(20);
            entity.Property(e => e.CommissionAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CommissionRate).HasColumnType("decimal(9, 4)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.SellerEarning).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SellerId).HasColumnName("SellerID");
            entity.Property(e => e.SellerStatus)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.CancelReason).WithMany(p => p.SellerOrders)
                .HasForeignKey(d => d.CancelReasonId)
                .HasConstraintName("FK_SellerOrders_CancelReason");

            entity.HasOne(d => d.Order).WithMany(p => p.SellerOrders)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SellerOrders_Order");
        });

        modelBuilder.Entity<SellerOrderItem>(entity =>
        {
            entity.HasKey(e => e.SellerOrderItemId).HasName("PK__SellerOr__CEF4003370300F7C");

            entity.Property(e => e.SellerOrderItemId).HasColumnName("SellerOrderItemID");
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.FinalAmount)
                .HasComputedColumnSql("([Quantity]*[UnitPrice]-[DiscountAmount])", true)
                .HasColumnType("decimal(30, 2)");
            entity.Property(e => e.FulfillmentType)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("SellerShip");
            entity.Property(e => e.ListingId).HasColumnName("ListingID");
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.SellerOrderId).HasColumnName("SellerOrderID");
            entity.Property(e => e.SnapshotAttributes).HasMaxLength(1000);
            entity.Property(e => e.SnapshotName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.SellerOrder).WithMany(p => p.SellerOrderItems)
                .HasForeignKey(d => d.SellerOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SellerOrderItems_SO");
        });

        modelBuilder.Entity<Shipment>(entity =>
        {
            entity.HasKey(e => e.ShipmentId).HasName("PK__Shipment__5CAD378D0ACDC2AD");

            entity.Property(e => e.ShipmentId).HasColumnName("ShipmentID");
            entity.Property(e => e.Carrier)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Codamount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("CODAmount");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeliveredAt).HasColumnType("datetime");
            entity.Property(e => e.HeightCm).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.LabelUrl).HasMaxLength(500);
            entity.Property(e => e.LengthCm).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.SellerOrderId).HasColumnName("SellerOrderID");
            entity.Property(e => e.ServiceLevel).HasMaxLength(50);
            entity.Property(e => e.ShippedAt).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.TrackingNumber).HasMaxLength(100);
            entity.Property(e => e.WarehouseId).HasColumnName("WarehouseID");
            entity.Property(e => e.WeightKg).HasColumnType("decimal(10, 3)");
            entity.Property(e => e.WidthCm).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.SellerOrder).WithMany(p => p.Shipments)
                .HasForeignKey(d => d.SellerOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Shipments_SO");
        });

        modelBuilder.Entity<ShipmentEvent>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("PK__Shipment__7944C870166E8523");

            entity.Property(e => e.EventId).HasColumnName("EventID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.EventAt).HasColumnType("datetime");
            entity.Property(e => e.EventCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.EventStatus).HasMaxLength(50);
            entity.Property(e => e.Location).HasMaxLength(255);
            entity.Property(e => e.ShipmentId).HasColumnName("ShipmentID");

            entity.HasOne(d => d.Shipment).WithMany(p => p.ShipmentEvents)
                .HasForeignKey(d => d.ShipmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ShipmentEvents_Shipment");
        });

        modelBuilder.Entity<Shipping>(entity =>
        {
            entity.HasKey(e => e.ShippingId).HasName("PK__Shipping__5FACD460E9B3CC0E");

            entity.ToTable("Shipping");

            entity.Property(e => e.ShippingId).HasColumnName("ShippingID");
            entity.Property(e => e.AddressDetail).HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ShippingType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StoreAddress).HasMaxLength(255);

            entity.HasOne(d => d.Order).WithMany(p => p.Shippings)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Shipping__OrderI__498EEC8D");
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.HasKey(e => e.StatusId).HasName("PK__Status__C8EE2043E8F9AEFE");

            entity.ToTable("Status");

            entity.HasIndex(e => e.IsActive, "IX_Status_IsActive");

            entity.HasIndex(e => e.StatusTypeId, "IX_Status_StatusTypeID");

            entity.Property(e => e.StatusId).HasColumnName("StatusID");
            entity.Property(e => e.ColorCode)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("#28a745");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Note).HasMaxLength(500);
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.StatusTypeId).HasColumnName("StatusTypeID");

            entity.HasOne(d => d.StatusType).WithMany(p => p.Statuses)
                .HasForeignKey(d => d.StatusTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Status_StatusType");
        });

        modelBuilder.Entity<StatusType>(entity =>
        {
            entity.HasKey(e => e.StatusTypeId).HasName("PK__StatusTy__A84F3D9327880826");

            entity.ToTable("StatusType");

            entity.HasIndex(e => e.StatusTypeName, "UQ__StatusTy__656B6258180D479D").IsUnique();

            entity.Property(e => e.StatusTypeId).HasColumnName("StatusTypeID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.StatusTypeName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<SupportConversation>(entity =>
        {
            entity.HasKey(e => e.ConversationId);

            entity.HasIndex(e => new { e.Status, e.StartedAt }, "IX_SupportConv_Status_Started").IsDescending(false, true);

            entity.Property(e => e.ClosedAt).HasColumnType("datetime");
            entity.Property(e => e.GuestId).HasMaxLength(100);
            entity.Property(e => e.StartedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SupportConversations_StartedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Open")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SupportConversations_Status");
        });

        modelBuilder.Entity<SupportMessage>(entity =>
        {
            entity.HasKey(e => e.MessageId);

            entity.HasIndex(e => new { e.ConversationId, e.CreatedAt }, "IX_SupportMsg_Conv_Created");

            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SupportMessages_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_SupportMessages_IsDeleted");
            entity.Property(e => e.IsRead).HasAnnotation("Relational:DefaultConstraintName", "DF_SupportMessages_IsRead");

            entity.HasOne(d => d.Conversation).WithMany(p => p.SupportMessages)
                .HasForeignKey(d => d.ConversationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SupportMsg_Conv");

            entity.HasOne(d => d.ReplyToMessage).WithMany(p => p.InverseReplyToMessage)
                .HasForeignKey(d => d.ReplyToMessageId)
                .HasConstraintName("FK_SupportMessages_ReplyTo");
        });

        modelBuilder.Entity<SupportMessageReaction>(entity =>
        {
            entity.HasKey(e => e.ReactionId);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SupportMessageReactions_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.ReactionType)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Message).WithMany(p => p.SupportMessageReactions)
                .HasForeignKey(d => d.MessageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SupportReactions_Message");
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}