// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using FreshFarm.Ordering.Api.Models;

namespace FreshFarm.Ordering.Api.Models
{
    public partial class FreshFarmOrderingDBContext
    {

        [DbFunction("ufn_Loyalty_IsPaid", "dbo")]
        public static bool? ufn_Loyalty_IsPaid(int? OrderID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("ufn_Loyalty_PaidWhen", "dbo")]
        public static DateTime? ufn_Loyalty_PaidWhen(int? OrderID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
