// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class InventoryReservation
{
    public int ReservationId { get; set; }

    public int InventoryId { get; set; }

    public int? OrderId { get; set; }

    public int? SellerOrderItemId { get; set; }

    public int Quantity { get; set; }

    public DateTime ExpiresAt { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual SellerOrderItem SellerOrderItem { get; set; }
}