// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class LoyaltyPointHistory
{
    public int PointHistoryId { get; set; }

    public int UserId { get; set; }

    public int? OrderId { get; set; }

    public int Points { get; set; }

    public string Direction { get; set; }

    public string Reason { get; set; }

    public DateTime CreatedAt { get; set; }
}