// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class LoyaltyConfig
{
    public int ConfigId { get; set; }

    public decimal EarnRate { get; set; }

    public bool IncludeShippingFee { get; set; }

    public string PaidKeywords { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}