// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class ModerationAudit
{
    public int ModerationAuditId { get; set; }

    public int? AdminActionLogId { get; set; }

    public string SubjectType { get; set; }

    public int? SubjectId { get; set; }

    public string Decision { get; set; }

    public string Notes { get; set; }

    public int? ActorUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual AdminActionLog AdminActionLog { get; set; }
}