// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class NotificationPreference
{
    public int NotificationPreferenceId { get; set; }

    public int UserId { get; set; }

    public string EventType { get; set; }

    public string Channel { get; set; }

    public bool IsOptedIn { get; set; }

    public string Source { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}