// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class NotificationPolicyRule
{
    public int NotificationPolicyRuleId { get; set; }

    public string EventType { get; set; }

    public string Channel { get; set; }

    public string AudienceType { get; set; }

    public int? CommunicationTemplateId { get; set; }

    public bool IsEnabled { get; set; }

    public int CooldownMinutes { get; set; }

    public string DeliveryMode { get; set; }

    public int Priority { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual CommunicationTemplate CommunicationTemplate { get; set; }
}