// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class OrderDetailInvalidProductArchive
{
    public long ArchiveId { get; set; }

    public int OrderDetailId { get; set; }

    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public string UnitSymbol { get; set; }

    public string Reason { get; set; }

    public DateTime ArchivedAt { get; set; }
}