// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int UserId { get; set; }

    public DateTime OrderDate { get; set; }

    public decimal ShippingFee { get; set; }

    public int? CouponId { get; set; }

    public decimal TotalAmount { get; set; }

    public string OrderNote { get; set; }

    public string Status { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? PaidAt { get; set; }

    public int? StatusId { get; set; }

    public string BuyerFullName { get; set; }

    public string BuyerPhone { get; set; }

    public string BuyerEmail { get; set; }

    public int PointsEarned { get; set; }

    public int PointsRedeemed { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual ICollection<CouponUsageHistory> CouponUsageHistories { get; set; } = new List<CouponUsageHistory>();

    public virtual ICollection<InventoryReservation> InventoryReservations { get; set; } = new List<InventoryReservation>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; } = new List<PaymentTransaction>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<ReconciliationLog> ReconciliationLogs { get; set; } = new List<ReconciliationLog>();

    public virtual ICollection<SellerOrder> SellerOrders { get; set; } = new List<SellerOrder>();

    public virtual ICollection<Shipping> Shippings { get; set; } = new List<Shipping>();

    public virtual Status StatusNavigation { get; set; }
}