// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class OrderStatusHistory
{
    public int HistoryId { get; set; }

    public string EntityType { get; set; }

    public int EntityId { get; set; }

    public string OldStatus { get; set; }

    public string NewStatus { get; set; }

    public string Note { get; set; }

    public string ActorType { get; set; }

    public int? ActorId { get; set; }

    public DateTime CreatedAt { get; set; }
}