// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class PaymentTransaction
{
    public int PaymentTxnId { get; set; }

    public int OrderId { get; set; }

    public string Provider { get; set; }

    public string Method { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public decimal? FeeAmount { get; set; }

    public string Status { get; set; }

    public string ProviderRef { get; set; }

    public string FailureCode { get; set; }

    public string FailureMessage { get; set; }

    public DateTime? PaidAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<Payout> Payouts { get; set; } = new List<Payout>();

    public virtual ICollection<RefundTransaction> RefundTransactions { get; set; } = new List<RefundTransaction>();
}