// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int OrderId { get; set; }

    public string PaymentMethod { get; set; }

    public string BankName { get; set; }

    public string AccountName { get; set; }

    public string AccountNumber { get; set; }

    public string TransactionCode { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? PaymentDate { get; set; }

    public int? UserId { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<ReconciliationLog> ReconciliationLogs { get; set; } = new List<ReconciliationLog>();
}