// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class PayoutItem
{
    public int PayoutItemId { get; set; }

    public int PayoutId { get; set; }

    public int SellerOrderId { get; set; }

    public decimal Amount { get; set; }

    public string Note { get; set; }

    public virtual Payout Payout { get; set; }

    public virtual SellerOrder SellerOrder { get; set; }
}