// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class Payout
{
    public int PayoutId { get; set; }

    public int SellerId { get; set; }

    public decimal AmountGross { get; set; }

    public decimal FeeAmount { get; set; }

    public decimal? AmountNet { get; set; }

    public string Status { get; set; }

    public DateTime? ScheduledAt { get; set; }

    public DateTime? PaidAt { get; set; }

    public int? PaymentTxnId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual PaymentTransaction PaymentTxn { get; set; }

    public virtual ICollection<PayoutItem> PayoutItems { get; set; } = new List<PayoutItem>();
}