// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class RefundTransaction
{
    public int RefundId { get; set; }

    public int PaymentTxnId { get; set; }

    public decimal Amount { get; set; }

    public string Status { get; set; }

    public string Channel { get; set; }

    public string ReferenceCode { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public virtual PaymentTransaction PaymentTxn { get; set; }
}