// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class ReturnRequest
{
    public int ReturnId { get; set; }

    public int SellerOrderItemId { get; set; }

    public int SellerId { get; set; }

    public string ReasonCode { get; set; }

    public string Description { get; set; }

    public string Photos { get; set; }

    public string Status { get; set; }

    public string Resolution { get; set; }

    public DateTime RequestedAt { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public decimal? RefundAmount { get; set; }

    public virtual SellerOrderItem SellerOrderItem { get; set; }
}