// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int ProductId { get; set; }

    public int UserId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? ReplyTo { get; set; }

    public bool IsApproved { get; set; }

    public bool IsEdited { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedByAdminId { get; set; }

    public virtual ICollection<Review> InverseReplyToNavigation { get; set; } = new List<Review>();

    public virtual Review ReplyToNavigation { get; set; }

    public virtual ICollection<ReviewReport> ReviewReports { get; set; } = new List<ReviewReport>();
}