// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class ReviewReport
{
    public int ReportId { get; set; }

    public int ReviewId { get; set; }

    public int ReporterUserId { get; set; }

    public string Reason { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Note { get; set; }

    public byte? Status { get; set; }

    public virtual Review Review { get; set; }
}