// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class RiskDecision
{
    public int RiskDecisionId { get; set; }

    public int RiskCaseId { get; set; }

    public string DecisionType { get; set; }

    public string Notes { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual RiskCase RiskCase { get; set; }
}