// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class RiskCase
{
    public int RiskCaseId { get; set; }

    public string ReferenceKey { get; set; }

    public string CaseType { get; set; }

    public string Status { get; set; }

    public string Severity { get; set; }

    public int? SellerId { get; set; }

    public int? BuyerId { get; set; }

    public int? OrderId { get; set; }

    public int? CampaignId { get; set; }

    public int? VoucherCouponId { get; set; }

    public string Title { get; set; }

    public string Summary { get; set; }

    public int SignalCount { get; set; }

    public bool IsEscalated { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? LastSignalAt { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public int? ReviewedBy { get; set; }

    public virtual ICollection<RiskDecision> RiskDecisions { get; set; } = new List<RiskDecision>();

    public virtual ICollection<RiskSignal> RiskSignals { get; set; } = new List<RiskSignal>();

    public virtual ICollection<VoucherAbuseCase> VoucherAbuseCases { get; set; } = new List<VoucherAbuseCase>();
}