// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class RiskSignal
{
    public int RiskSignalId { get; set; }

    public int RiskCaseId { get; set; }

    public string ReferenceKey { get; set; }

    public string SignalType { get; set; }

    public string SignalCode { get; set; }

    public string Severity { get; set; }

    public string Source { get; set; }

    public decimal Score { get; set; }

    public int? SellerId { get; set; }

    public int? BuyerId { get; set; }

    public int? OrderId { get; set; }

    public int? CampaignId { get; set; }

    public int? VoucherCouponId { get; set; }

    public string MetadataJson { get; set; }

    public DateTime TriggeredAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual RiskCase RiskCase { get; set; }
}