// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class SellerAdsWallet
{
    public int WalletId { get; set; }

    public int SellerId { get; set; }

    public decimal Balance { get; set; }

    public decimal ReservedBalance { get; set; }

    public decimal TotalTopup { get; set; }

    public decimal TotalSpend { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<AdsCampaign> AdsCampaigns { get; set; } = new List<AdsCampaign>();

    public virtual ICollection<AdsSpendLedger> AdsSpendLedgers { get; set; } = new List<AdsSpendLedger>();

    public virtual ICollection<AdsTopup> AdsTopups { get; set; } = new List<AdsTopup>();
}