// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace FreshFarm.Ordering.Api.Models;

public partial class SellerCommissionSetting
{
    public int SellerCommissionSettingId { get; set; }

    public int? SellerId { get; set; }

    public decimal CommissionRate { get; set; }

    public bool IsActive { get; set; }

    public DateTime EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}
