// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class SellerOrder
{
    public int SellerOrderId { get; set; }

    public int OrderId { get; set; }

    public int SellerId { get; set; }

    public string SellerStatus { get; set; }

    public decimal CommissionRate { get; set; }

    public decimal CommissionAmount { get; set; }

    public decimal ShippingFee { get; set; }

    public decimal SellerEarning { get; set; }

    public string CancelledBy { get; set; }

    public int? CancelReasonId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual CancelReason CancelReason { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<PayoutItem> PayoutItems { get; set; } = new List<PayoutItem>();

    public virtual ICollection<SellerOrderItem> SellerOrderItems { get; set; } = new List<SellerOrderItem>();

    public virtual ICollection<Shipment> Shipments { get; set; } = new List<Shipment>();
}
