// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class SellerOrderItem
{
    public int SellerOrderItemId { get; set; }

    public int SellerOrderId { get; set; }

    public int ListingId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal DiscountAmount { get; set; }

    public string SnapshotName { get; set; }

    public string SnapshotAttributes { get; set; }

    public string FulfillmentType { get; set; }

    public decimal? FinalAmount { get; set; }

    public virtual ICollection<InventoryReservation> InventoryReservations { get; set; } = new List<InventoryReservation>();

    public virtual ICollection<ReturnRequest> ReturnRequests { get; set; } = new List<ReturnRequest>();

    public virtual SellerOrder SellerOrder { get; set; }
}