// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class SettlementAudit
{
    public int SettlementAuditId { get; set; }

    public int? AdminActionLogId { get; set; }

    public string AuditType { get; set; }

    public string ReferenceType { get; set; }

    public int? ReferenceId { get; set; }

    public int? SellerId { get; set; }

    public decimal? Amount { get; set; }

    public string Currency { get; set; }

    public string Notes { get; set; }

    public int? ActorUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual AdminActionLog AdminActionLog { get; set; }
}