// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class ShipmentEvent
{
    public int EventId { get; set; }

    public int ShipmentId { get; set; }

    public string EventCode { get; set; }

    public string EventStatus { get; set; }

    public DateTime EventAt { get; set; }

    public string Location { get; set; }

    public string RawPayload { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Shipment Shipment { get; set; }
}