// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class Shipment
{
    public int ShipmentId { get; set; }

    public int SellerOrderId { get; set; }

    public int? WarehouseId { get; set; }

    public string Carrier { get; set; }

    public string ServiceLevel { get; set; }

    public string TrackingNumber { get; set; }

    public string LabelUrl { get; set; }

    public string Status { get; set; }

    public decimal? Codamount { get; set; }

    public decimal? WeightKg { get; set; }

    public decimal? LengthCm { get; set; }

    public decimal? WidthCm { get; set; }

    public decimal? HeightCm { get; set; }

    public DateTime? ShippedAt { get; set; }

    public DateTime? DeliveredAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual SellerOrder SellerOrder { get; set; }

    public virtual ICollection<ShipmentEvent> ShipmentEvents { get; set; } = new List<ShipmentEvent>();
}