// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class Shipping
{
    public int ShippingId { get; set; }

    public int OrderId { get; set; }

    public string ShippingType { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string AddressDetail { get; set; }

    public int? ProvinceId { get; set; }

    public int? CommuneId { get; set; }

    public string GhnOrderCode { get; set; }

    public string GhnClientOrderCode { get; set; }

    public string GhnStatus { get; set; }

    public string GhnStatusLabel { get; set; }

    public decimal? GhnTotalFee { get; set; }

    public DateTime? GhnCreatedAt { get; set; }

    public DateTime? GhnExpectedDeliveryTime { get; set; }

    public DateTime? GhnLastSyncedAt { get; set; }

    public bool IsStorePickup { get; set; }

    public string StoreAddress { get; set; }

    public virtual Order Order { get; set; }
}
