// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class Status
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public int StatusTypeId { get; set; }

    public string ColorCode { get; set; }

    public string Note { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual StatusType StatusType { get; set; }
}