// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class SupportMessage
{
    public int MessageId { get; set; }

    public int ConversationId { get; set; }

    public byte SenderType { get; set; }

    public int? SenderUserId { get; set; }

    public int? SenderAdminId { get; set; }

    public string Content { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsRead { get; set; }

    public int? ReplyToMessageId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual SupportConversation Conversation { get; set; }

    public virtual ICollection<SupportMessage> InverseReplyToMessage { get; set; } = new List<SupportMessage>();

    public virtual SupportMessage ReplyToMessage { get; set; }

    public virtual ICollection<SupportMessageReaction> SupportMessageReactions { get; set; } = new List<SupportMessageReaction>();
}