// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class SupportMessageReaction
{
    public int ReactionId { get; set; }

    public int MessageId { get; set; }

    public int? UserId { get; set; }

    public int? AdminId { get; set; }

    public string ReactionType { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual SupportMessage Message { get; set; }
}