// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class SupportConversation
{
    public int ConversationId { get; set; }

    public int? UserId { get; set; }

    public string GuestId { get; set; }

    public int? AdminId { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? ClosedAt { get; set; }

    public string Status { get; set; }

    public virtual ICollection<SupportMessage> SupportMessages { get; set; } = new List<SupportMessage>();
}