// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Ordering.Api.Models;

public partial class VoucherAbuseCase
{
    public int VoucherAbuseCaseId { get; set; }

    public string ReferenceKey { get; set; }

    public int RiskCaseId { get; set; }

    public int CouponId { get; set; }

    public int? BuyerId { get; set; }

    public int? SellerId { get; set; }

    public int? CampaignId { get; set; }

    public int? OrderId { get; set; }

    public string AbuseType { get; set; }

    public decimal? SuspectedBenefitAmount { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public virtual RiskCase RiskCase { get; set; }
}