// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Catalog.Api.Models;

public partial class CategoryAttribute
{
    public int CategoryAttributeId { get; set; }

    public int CategoryId { get; set; }

    public string AttributeKey { get; set; }

    public string DisplayName { get; set; }

    public string InputType { get; set; }

    public bool IsRequired { get; set; }

    public bool IsFacet { get; set; }

    public int SortOrder { get; set; }

    public string Placeholder { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}