// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Catalog.Api.Models;

public partial class ProductInfo
{
    public int InfoId { get; set; }

    public int ProductId { get; set; }

    public string Weight { get; set; }

    public string Origin { get; set; }

    public string Standard { get; set; }

    public string Preservation { get; set; }

    public virtual Product Product { get; set; }
}