// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Catalog.Api.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public int CategoryId { get; set; }

    public string ProductName { get; set; }

    public string Sku { get; set; }

    public decimal Price { get; set; }

    public bool Status { get; set; }

    public int StockQuantity { get; set; }

    public string ImageFileName { get; set; }

    public DateTime CreatedDate { get; set; }

    public string ShortDescription { get; set; }

    public string LongDescription { get; set; }

    public int UnitId { get; set; }

    public int? NearExpiryDays { get; set; }

    public bool IsManuallyDisabled { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    public virtual ICollection<ProductInfo> ProductInfos { get; set; } = new List<ProductInfo>();

    public virtual ICollection<SellerProduct> SellerProducts { get; set; } = new List<SellerProduct>();

    public virtual Unit Unit { get; set; }
}