// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Catalog.Api.Models;

public partial class Unit
{
    public int UnitId { get; set; }

    public string UnitName { get; set; }

    public string Symbol { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}