// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Catalog.Api.Models;

public partial class Category
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public string ImageCategoriesName { get; set; }

    public bool IsActive { get; set; }

    public string Slug { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? NearExpiryDays { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}