// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Identity.Api.Models;

public partial class AddressBook
{
    public int AddressId { get; set; }

    public int UserId { get; set; }

    public string RecipientName { get; set; }

    public string Phone { get; set; }

    public string AddressDetail { get; set; }

    public string Province { get; set; }

    public string District { get; set; }

    public string Ward { get; set; }

    public bool IsDefault { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User User { get; set; }
}