// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FreshFarm.Identity.Api.Models;

public partial class FreshFarmIdentityDBContext : DbContext
{
    public FreshFarmIdentityDBContext(DbContextOptions<FreshFarmIdentityDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AddressBook> AddressBooks { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolePermission> RolePermissions { get; set; }

    public virtual DbSet<SellerStoreSetting> SellerStoreSettings { get; set; }

    public virtual DbSet<StoreSetting> StoreSettings { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserAuth> UserAuths { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AddressBook>(entity =>
        {
            entity.HasKey(e => e.AddressId);

            entity.ToTable("AddressBook");

            entity.HasIndex(e => new { e.UserId, e.IsActive, e.IsDefault }, "IX_AddressBook_UserId_IsActive");

            entity.HasIndex(e => e.UserId, "UX_AddressBook_Default_OnePerUser")
                .IsUnique()
                .HasFilter("([IsDefault]=(1) AND [IsActive]=(1))");

            entity.Property(e => e.AddressDetail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AddressBook_CreatedAt");
            entity.Property(e => e.District).HasMaxLength(100);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AddressBook_IsActive");
            entity.Property(e => e.IsDefault).HasAnnotation("Relational:DefaultConstraintName", "DF_AddressBook_IsDefault");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Province).HasMaxLength(100);
            entity.Property(e => e.RecipientName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
            entity.Property(e => e.Ward).HasMaxLength(100);

            entity.HasOne(d => d.User).WithOne(p => p.AddressBook)
                .HasForeignKey<AddressBook>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AddressBook_Users");
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasIndex(e => e.PermissionCode, "UQ_Permissions_Code").IsUnique();

            entity.HasIndex(e => e.PermissionName, "UQ_Permissions_Name").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Permissions_CreatedAt");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Permissions_IsActive");
            entity.Property(e => e.ModuleName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PermissionCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PermissionName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasIndex(e => e.RoleName, "UQ_Roles_RoleName").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Roles_CreatedAt");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Roles_IsActive");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.HasKey(e => new { e.RoleId, e.PermissionId });

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RolePermissions_CreatedAt");

            entity.HasOne(d => d.Permission).WithMany(p => p.RolePermissions)
                .HasForeignKey(d => d.PermissionId)
                .HasConstraintName("FK_RolePermissions_Permissions");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePermissions)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_RolePermissions_Roles");
        });

        modelBuilder.Entity<SellerStoreSetting>(entity =>
        {
            entity.HasIndex(e => e.UserId, "UX_SellerStoreSettings_UserId").IsUnique();

            entity.Property(e => e.AdminNotificationEmail)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_CreatedAt");
            entity.Property(e => e.DefaultShippingFee)
                .HasDefaultValue(30000m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_DefaultShippingFee")
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.FreeShippingThreshold)
                .HasDefaultValue(500000m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_FreeShippingThreshold")
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.GhnDistrictName).HasMaxLength(150);
            entity.Property(e => e.GhnPickupAddress).HasMaxLength(500);
            entity.Property(e => e.GhnPickupName).HasMaxLength(150);
            entity.Property(e => e.GhnPickupPhone).HasMaxLength(20);
            entity.Property(e => e.GhnProvinceName).HasMaxLength(150);
            entity.Property(e => e.GhnWardCode).HasMaxLength(50);
            entity.Property(e => e.GhnWardName).HasMaxLength(150);
            entity.Property(e => e.IsCodenabled)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_IsCODEnabled")
                .HasColumnName("IsCODEnabled");
            entity.Property(e => e.IsEmailCancelledEnabled)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_IsEmailCancelledEnabled");
            entity.Property(e => e.IsEmailDeliveredEnabled)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_IsEmailDeliveredEnabled");
            entity.Property(e => e.IsEmailNewOrderEnabled)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_IsEmailNewOrderEnabled");
            entity.Property(e => e.StoreAddress)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.StoreEmail)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.StoreName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.StorePhone)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_UpdatedAt");

            entity.HasOne(d => d.User).WithOne(p => p.SellerStoreSetting)
                .HasForeignKey<SellerStoreSetting>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SellerStoreSettings_Users");
        });

        modelBuilder.Entity<StoreSetting>(entity =>
        {
            entity.HasKey(e => e.SettingId);

            entity.Property(e => e.SettingId).HasColumnName("SettingID");
            entity.Property(e => e.AdminNotificationEmail)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_StoreSettings_CreatedAt");
            entity.Property(e => e.DefaultShippingFee).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.FreeShippingThreshold).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.IsCodenabled).HasColumnName("IsCODEnabled");
            entity.Property(e => e.StoreAddress)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.StoreEmail)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.StoreName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.StorePhone)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_StoreSettings_UpdatedAt");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasIndex(e => e.Email, "UQ_Users_Email").IsUnique();

            entity.HasIndex(e => e.Phone, "UQ_Users_Phone").IsUnique();

            entity.HasIndex(e => e.UserName, "UQ_Users_UserName").IsUnique();

            entity.Property(e => e.Avatar).HasMaxLength(255);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_CreatedAt");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_IsActive");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.UpdatedAt).HasPrecision(0);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<UserAuth>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("UserAuth");

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.FailedCount).HasAnnotation("Relational:DefaultConstraintName", "DF_UserAuth_FailedCount");
            entity.Property(e => e.LockedUntil).HasPrecision(0);
            entity.Property(e => e.Mfasecret)
                .HasMaxLength(100)
                .HasColumnName("MFASecret");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(450);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserAuth_UpdatedAt");

            entity.HasOne(d => d.User).WithOne(p => p.UserAuth)
                .HasForeignKey<UserAuth>(d => d.UserId)
                .HasConstraintName("FK_UserAuth_Users");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId });

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoles_CreatedAt");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_UserRoles_Roles");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserRoles_Users");
        });

        modelBuilder.Entity<UserSession>(entity =>
        {
            entity.HasKey(e => e.SessionId);

            entity.HasIndex(e => e.RefreshToken, "UQ_UserSessions_RefreshToken").IsUnique();

            entity.Property(e => e.SessionId)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSessions_SessionId");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSessions_CreatedAt");
            entity.Property(e => e.ExpiresAt).HasPrecision(0);
            entity.Property(e => e.RefreshToken)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.RevokedAt).HasPrecision(0);

            entity.HasOne(d => d.User).WithMany(p => p.UserSessions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserSessions_Users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}