// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Identity.Api.Models;

public partial class Permission
{
    public int PermissionId { get; set; }

    public string PermissionName { get; set; }

    public string PermissionCode { get; set; }

    public string ModuleName { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();
}