// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Identity.Api.Models;

public partial class SellerStoreSetting
{
    public int SellerStoreSettingId { get; set; }

    public int UserId { get; set; }

    public string StoreName { get; set; }

    public string StoreAddress { get; set; }

    public string StoreEmail { get; set; }

    public string StorePhone { get; set; }

    public bool IsCodenabled { get; set; }

    public string BankTransferInstructions { get; set; }

    public string BankAccountInfo { get; set; }

    public decimal DefaultShippingFee { get; set; }

    public decimal FreeShippingThreshold { get; set; }

    public bool IsEmailNewOrderEnabled { get; set; }

    public bool IsEmailDeliveredEnabled { get; set; }

    public bool IsEmailCancelledEnabled { get; set; }

    public string AdminNotificationEmail { get; set; }

    public string GhnPickupName { get; set; }

    public string GhnPickupPhone { get; set; }

    public string GhnPickupAddress { get; set; }

    public int? GhnProvinceId { get; set; }

    public string GhnProvinceName { get; set; }

    public int? GhnDistrictId { get; set; }

    public string GhnDistrictName { get; set; }

    public string GhnWardCode { get; set; }

    public string GhnWardName { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User User { get; set; }
}