// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Identity.Api.Models;

public partial class StoreSetting
{
    public int SettingId { get; set; }

    public string StoreName { get; set; }

    public string StoreAddress { get; set; }

    public string StoreEmail { get; set; }

    public string StorePhone { get; set; }

    public bool IsCodenabled { get; set; }

    public string BankTransferInstructions { get; set; }

    public string BankAccountInfo { get; set; }

    public decimal DefaultShippingFee { get; set; }

    public decimal FreeShippingThreshold { get; set; }

    public bool IsEmailNewOrderEnabled { get; set; }

    public bool IsEmailDeliveredEnabled { get; set; }

    public bool IsEmailCancelledEnabled { get; set; }

    public string AdminNotificationEmail { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}