// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FreshFarm.Identity.Api.Models;

public partial class UserAuth
{
    public int UserId { get; set; }

    public string PasswordHash { get; set; }

    public int FailedCount { get; set; }

    public DateTime? LockedUntil { get; set; }

    public int LockoutLevel { get; set; }

    public string Mfasecret { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User User { get; set; }
}
