// <auto-generated />
using System;
using FreshFarm.Catalog.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreshFarm.Catalog.Api.Migrations
{
    [DbContext(typeof(FreshFarmCatalogDBContext))]
    partial class FreshFarmCatalogDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Categories_CreatedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageCategoriesName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("NearExpiryDays")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A2BD446118F");

                    b.HasIndex(new[] { "IsActive" }, "IX_Categories_IsActive");

                    b.HasIndex(new[] { "CategoryName" }, "UQ_Categories_CategoryName")
                        .IsUnique();

                    b.HasIndex(new[] { "Slug" }, "UQ_Categories_Slug")
                        .IsUnique()
                        .HasFilter("([Slug] IS NOT NULL)");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.CategoryAttribute", b =>
                {
                    b.Property<int>("CategoryAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryAttributeId"));

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_CategoryAttribute_CreatedAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("text")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_CategoryAttribute_InputType");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_CategoryAttribute_IsActive");

                    b.Property<bool>("IsFacet")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_CategoryAttribute_IsFacet");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_CategoryAttribute_IsRequired");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_CategoryAttribute_SortOrder");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("CategoryAttributeId");

                    b.HasIndex(new[] { "CategoryId", "IsRequired", "IsActive" }, "IX_CategoryAttribute_Category_Required_Active");

                    b.HasIndex(new[] { "CategoryId", "AttributeKey" }, "UQ_CategoryAttribute_Category_Key")
                        .IsUnique();

                    b.ToTable("CategoryAttribute", (string)null);
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.FreshInventoryLot", b =>
                {
                    b.Property<int>("FreshInventoryLotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FreshInventoryLotId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<string>("FarmName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("HarvestedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("int");

                    b.Property<string>("LotCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OriginRegion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("PackedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("QualityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("ok");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("active");

                    b.Property<string>("TraceCode")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("FreshInventoryLotId");

                    b.HasIndex(new[] { "ProductId", "Status" }, "IX_FreshInventoryLot_Product_Status");

                    b.HasIndex(new[] { "SellerId", "ExpiresAt" }, "IX_FreshInventoryLot_Seller_ExpiresAt");

                    b.HasIndex(new[] { "SellerId", "ProductId", "LotCode" }, "UQ_FreshInventoryLot_Seller_Product_Lot")
                        .IsUnique();

                    b.ToTable("FreshInventoryLot", (string)null);
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.FreshQualityRecall", b =>
                {
                    b.Property<int>("FreshQualityRecallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FreshQualityRecallId"));

                    b.Property<string>("ActionRequired")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("FreshInventoryLotId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RecallCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecallType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("medium");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("FreshQualityRecallId");

                    b.HasIndex("FreshInventoryLotId");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "SellerId", "Severity" }, "IX_FreshQualityRecall_Seller_Severity");

                    b.HasIndex(new[] { "Status", "StartedAt" }, "IX_FreshQualityRecall_Status_StartedAt");

                    b.HasIndex(new[] { "RecallCode" }, "UQ_FreshQualityRecall_Code")
                        .IsUnique();

                    b.ToTable("FreshQualityRecall", (string)null);
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsManuallyDisabled")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Products_IsManuallyDisabled");

                    b.Property<string>("LongDescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Products_LongDescription");

                    b.Property<int?>("NearExpiryDays")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ReservedStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Products_ReservedStock");

                    b.Property<string>("ShortDescription")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasDefaultValue("")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Products_ShortDescription");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitID");

                    b.HasKey("ProductId")
                        .HasName("PK__Products__B40CC6ED90295002");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitId");

                    b.HasIndex(new[] { "Sku" }, "UQ__Products__CA1FD3C56FD37852")
                        .IsUnique()
                        .HasFilter("[Sku] IS NOT NULL");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.ProductAttributeValue", b =>
                {
                    b.Property<int>("ProductAttributeValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductAttributeValueId"));

                    b.Property<int>("CategoryAttributeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("NormalizedValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("manual");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ValueText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ProductAttributeValueId");

                    b.HasIndex(new[] { "CategoryAttributeId", "NormalizedValue" }, "IX_ProductAttributeValue_Attribute_NormalizedValue");

                    b.HasIndex(new[] { "ProductId", "CategoryAttributeId" }, "UQ_ProductAttributeValue_Product_Attribute")
                        .IsUnique();

                    b.ToTable("ProductAttributeValue", (string)null);
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.HasKey("ImageId")
                        .HasName("PK__ProductI__7516F4EC627BBD39");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage", (string)null);
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.ProductInfo", b =>
                {
                    b.Property<int>("InfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InfoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfoId"));

                    b.Property<string>("Origin")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Preservation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<string>("Standard")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Weight")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InfoId")
                        .HasName("PK__ProductI__4DEC9D9AFB02F334");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInfo", (string)null);
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.SellerProduct", b =>
                {
                    b.Property<int>("SellerProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SellerProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellerProductId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerProducts_CreatedAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerProducts_IsActive");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("SellerID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("SellerProductId");

                    b.HasIndex(new[] { "ProductId", "IsActive" }, "IX_SellerProducts_Product_IsActive");

                    b.HasIndex(new[] { "SellerId", "IsActive" }, "IX_SellerProducts_Seller_IsActive");

                    b.HasIndex(new[] { "SellerId", "ProductId" }, "UX_SellerProducts_Seller_Product")
                        .IsUnique();

                    b.ToTable("SellerProducts");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UnitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UnitId");

                    b.HasIndex(new[] { "Symbol" }, "UX_Unit_Symbol")
                        .IsUnique();

                    b.HasIndex(new[] { "UnitName" }, "UX_Unit_UnitName")
                        .IsUnique();

                    b.ToTable("Unit", (string)null);
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.CategoryAttribute", b =>
                {
                    b.HasOne("FreshFarm.Catalog.Api.Models.Category", "Category")
                        .WithMany("CategoryAttributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CategoryAttribute_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.FreshInventoryLot", b =>
                {
                    b.HasOne("FreshFarm.Catalog.Api.Models.Product", "Product")
                        .WithMany("FreshInventoryLots")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FreshInventoryLot_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.FreshQualityRecall", b =>
                {
                    b.HasOne("FreshFarm.Catalog.Api.Models.FreshInventoryLot", "FreshInventoryLot")
                        .WithMany()
                        .HasForeignKey("FreshInventoryLotId")
                        .HasConstraintName("FK_FreshQualityRecall_FreshInventoryLot");

                    b.HasOne("FreshFarm.Catalog.Api.Models.Product", "Product")
                        .WithMany("FreshQualityRecalls")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_FreshQualityRecall_Product");

                    b.Navigation("FreshInventoryLot");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.Product", b =>
                {
                    b.HasOne("FreshFarm.Catalog.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Products__Catego__4D94879B");

                    b.HasOne("FreshFarm.Catalog.Api.Models.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Unit");

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.ProductAttributeValue", b =>
                {
                    b.HasOne("FreshFarm.Catalog.Api.Models.CategoryAttribute", "CategoryAttribute")
                        .WithMany("ProductAttributeValues")
                        .HasForeignKey("CategoryAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductAttributeValue_CategoryAttribute");

                    b.HasOne("FreshFarm.Catalog.Api.Models.Product", "Product")
                        .WithMany("ProductAttributeValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductAttributeValue_Product");

                    b.Navigation("CategoryAttribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.ProductImage", b =>
                {
                    b.HasOne("FreshFarm.Catalog.Api.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductIm__Produ__4BAC3F29");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.ProductInfo", b =>
                {
                    b.HasOne("FreshFarm.Catalog.Api.Models.Product", "Product")
                        .WithMany("ProductInfos")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductIn__Produ__4CA06362");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.SellerProduct", b =>
                {
                    b.HasOne("FreshFarm.Catalog.Api.Models.Product", "Product")
                        .WithMany("SellerProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SellerProducts_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.Category", b =>
                {
                    b.Navigation("CategoryAttributes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.CategoryAttribute", b =>
                {
                    b.Navigation("ProductAttributeValues");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.Product", b =>
                {
                    b.Navigation("FreshInventoryLots");

                    b.Navigation("FreshQualityRecalls");

                    b.Navigation("ProductAttributeValues");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductInfos");

                    b.Navigation("SellerProducts");
                });

            modelBuilder.Entity("FreshFarm.Catalog.Api.Models.Unit", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
