// <auto-generated />
using System;
using FreshFarm.Identity.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreshFarm.Identity.Api.Migrations
{
    [DbContext(typeof(FreshFarmIdentityDBContext))]
    [Migration("20260324135630_IdentitySchemaBaseline20260324")]
    partial class IdentitySchemaBaseline20260324
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.AddressBook", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_AddressBook_CreatedAt");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_AddressBook_IsActive");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_AddressBook_IsDefault");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AddressId");

                    b.HasIndex(new[] { "UserId", "IsActive", "IsDefault" }, "IX_AddressBook_UserId_IsActive");

                    b.HasIndex(new[] { "UserId" }, "UX_AddressBook_Default_OnePerUser")
                        .IsUnique()
                        .HasFilter("([IsDefault]=(1) AND [IsActive]=(1))");

                    b.ToTable("AddressBook", (string)null);
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.AuthAuditLog", b =>
                {
                    b.Property<int>("AuthAuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthAuditLogId"));

                    b.Property<string>("BrowserFamily")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CityName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ClientLane")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CountryName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FailedAttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ForwardedFor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsSuspicious")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_AuthAuditLog_IsSuspicious");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_AuthAuditLog_OccurredAt");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegionName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<string>("SuspicionReasons")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuthAuditLogId");

                    b.HasIndex(new[] { "ClientLane", "OccurredAt" }, "IX_AuthAuditLog_ClientLane_OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "IsSuspicious", "OccurredAt" }, "IX_AuthAuditLog_IsSuspicious_OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "OccurredAt" }, "IX_AuthAuditLog_OccurredAt")
                        .IsDescending();

                    b.HasIndex(new[] { "RoleName", "OccurredAt" }, "IX_AuthAuditLog_RoleName_OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "Success", "OccurredAt" }, "IX_AuthAuditLog_Success_OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "UserId", "OccurredAt" }, "IX_AuthAuditLog_UserId_OccurredAt")
                        .IsDescending(false, true);

                    b.ToTable("AuthAuditLog", (string)null);
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Permissions_CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Permissions_IsActive");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermissionId");

                    b.HasIndex(new[] { "PermissionCode" }, "UQ_Permissions_Code")
                        .IsUnique();

                    b.HasIndex(new[] { "PermissionName" }, "UQ_Permissions_Name")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Roles_CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Roles_IsActive");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "RoleName" }, "UQ_Roles_RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_RolePermissions_CreatedAt");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.SellerKycProfile", b =>
                {
                    b.Property<int>("SellerKycProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellerKycProfileId"));

                    b.Property<string>("AdditionalDocumentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BusinessLicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BusinessLicenseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CitizenIdBackUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CitizenIdFrontUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("IdentityIssuedDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("IdentityIssuedPlace")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LegalFullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SellerKycProfileId");

                    b.HasIndex(new[] { "UserId" }, "UX_SellerKycProfiles_UserId")
                        .IsUnique();

                    b.ToTable("SellerKycProfiles", (string)null);
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.SellerKycReviewEvent", b =>
                {
                    b.Property<int>("SellerKycReviewEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellerKycReviewEventId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ReviewedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerFullName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReviewerUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SellerKycReviewEventId");

                    b.HasIndex(new[] { "UserId", "ReviewedAt" }, "IX_SellerKycReviewEvents_UserId_ReviewedAt")
                        .IsDescending(false, true);

                    b.ToTable("SellerKycReviewEvents", (string)null);
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.SellerStoreSetting", b =>
                {
                    b.Property<int>("SellerStoreSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellerStoreSettingId"));

                    b.Property<string>("AdminNotificationEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BankAccountInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankTransferInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_CreatedAt");

                    b.Property<decimal>("DefaultShippingFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(30000m)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_DefaultShippingFee");

                    b.Property<decimal>("FreeShippingThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(500000m)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_FreeShippingThreshold");

                    b.Property<int?>("GhnDistrictId")
                        .HasColumnType("int");

                    b.Property<string>("GhnDistrictName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GhnPickupAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhnPickupName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GhnPickupPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GhnProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("GhnProvinceName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GhnWardCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhnWardName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsCodenabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsCODEnabled")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_IsCODEnabled");

                    b.Property<bool>("IsEmailCancelledEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_IsEmailCancelledEnabled");

                    b.Property<bool>("IsEmailDeliveredEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_IsEmailDeliveredEnabled");

                    b.Property<bool>("IsEmailNewOrderEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_IsEmailNewOrderEnabled");

                    b.Property<string>("StoreAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StoreEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StorePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_SellerStoreSettings_UpdatedAt");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SellerStoreSettingId");

                    b.HasIndex(new[] { "UserId" }, "UX_SellerStoreSettings_UserId")
                        .IsUnique();

                    b.ToTable("SellerStoreSettings");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.StoreSetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SettingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("AdminNotificationEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BankAccountInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankTransferInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_StoreSettings_CreatedAt");

                    b.Property<decimal>("DefaultShippingFee")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("FreeShippingThreshold")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool>("IsCodenabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsCODEnabled");

                    b.Property<bool>("IsEmailCancelledEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailDeliveredEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailNewOrderEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("StoreAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StoreEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StorePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_StoreSettings_UpdatedAt");

                    b.HasKey("SettingId");

                    b.ToTable("StoreSettings");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_EmailConfirmed");

                    b.Property<DateTime?>("EmailConfirmedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_IsActive");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "UQ_Users_Phone")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "UQ_Users_UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.UserAuth", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_UserAuth_FailedCount");

                    b.Property<DateTime?>("LockedUntil")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("LockoutLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_UserAuth_LockoutLevel");

                    b.Property<string>("Mfasecret")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MFASecret");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_UserAuth_UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("UserAuth", (string)null);
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_UserRoles_CreatedAt");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.UserSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSessions_SessionId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_UserSessions_CreatedAt");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "RefreshToken" }, "UQ_UserSessions_RefreshToken")
                        .IsUnique();

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.AddressBook", b =>
                {
                    b.HasOne("FreshFarm.Identity.Api.Models.User", "User")
                        .WithOne("AddressBook")
                        .HasForeignKey("FreshFarm.Identity.Api.Models.AddressBook", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AddressBook_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.AuthAuditLog", b =>
                {
                    b.HasOne("FreshFarm.Identity.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AuthAuditLog_Users");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.RolePermission", b =>
                {
                    b.HasOne("FreshFarm.Identity.Api.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Permissions");

                    b.HasOne("FreshFarm.Identity.Api.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Roles");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.SellerKycProfile", b =>
                {
                    b.HasOne("FreshFarm.Identity.Api.Models.User", "User")
                        .WithOne("SellerKycProfile")
                        .HasForeignKey("FreshFarm.Identity.Api.Models.SellerKycProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SellerKycProfiles_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.SellerStoreSetting", b =>
                {
                    b.HasOne("FreshFarm.Identity.Api.Models.User", "User")
                        .WithOne("SellerStoreSetting")
                        .HasForeignKey("FreshFarm.Identity.Api.Models.SellerStoreSetting", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_SellerStoreSettings_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.UserAuth", b =>
                {
                    b.HasOne("FreshFarm.Identity.Api.Models.User", "User")
                        .WithOne("UserAuth")
                        .HasForeignKey("FreshFarm.Identity.Api.Models.UserAuth", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAuth_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.UserRole", b =>
                {
                    b.HasOne("FreshFarm.Identity.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("FreshFarm.Identity.Api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.UserSession", b =>
                {
                    b.HasOne("FreshFarm.Identity.Api.Models.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSessions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FreshFarm.Identity.Api.Models.User", b =>
                {
                    b.Navigation("AddressBook");

                    b.Navigation("SellerKycProfile");

                    b.Navigation("SellerStoreSetting");

                    b.Navigation("UserAuth");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
